# Generated by Django 5.2.7 on 2025-10-26 12:24

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import typing
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSession",
            fields=[
                ("user", models.CharField(max_length=50)),
                ("key", models.CharField(max_length=50)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user",
                        "key",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=50)),
                ("cookies", models.JSONField(blank=True, default=list, null=True)),
                ("config", models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=150, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_id", models.CharField(max_length=20)),
                ("sub_type", models.CharField(max_length=20)),
                ("type", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "amt",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("moc", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Discount",
            },
        ),
        migrations.CreateModel(
            name="DmgShtReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inum",
                    models.CharField(max_length=100, verbose_name="Damage Invoice No"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("damage", "damage"), ("shortage", "shortage")],
                        max_length=50,
                        verbose_name="Type (Damage or Shortage)",
                    ),
                ),
                (
                    "return_from",
                    models.CharField(
                        choices=[("market", "market"), ("rs", "rs")],
                        max_length=100,
                        verbose_name="Return From (Market/RS)",
                    ),
                ),
                ("date", models.DateField(verbose_name="Damage Date")),
                (
                    "party_id",
                    models.CharField(max_length=100, verbose_name="Retailer Code"),
                ),
                (
                    "party_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Retailer Name"
                    ),
                ),
                (
                    "stock_id",
                    models.CharField(max_length=50, verbose_name="Product Code"),
                ),
                (
                    "desc",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Product Name"
                    ),
                ),
                ("qty", models.IntegerField(verbose_name="Quantity")),
                (
                    "amt",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total TUR Value"
                    ),
                ),
                (
                    "plg",
                    models.CharField(
                        max_length=100, null=True, verbose_name="PLG (DETS,FNB,..)"
                    ),
                ),
                (
                    "credit_note_no",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Credit Note No"
                    ),
                ),
                (
                    "original_invoice_no",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Original Invoice No"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
            ],
            options={
                "db_table": "dmgsht_report",
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.CreateModel(
            name="GSTR1Portal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(max_length=6, verbose_name="Period (MMYYYY)"),
                ),
                ("date", models.DateField(verbose_name="Invoice Date")),
                ("inum", models.CharField(max_length=30, verbose_name="Invoice No")),
                (
                    "type",
                    models.CharField(max_length=10, verbose_name="Type (b2b/cdnr)"),
                ),
                (
                    "ctin",
                    models.CharField(
                        max_length=20, null=True, verbose_name="GSTIN of Recipient"
                    ),
                ),
                (
                    "amt",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Invoice Amount"
                    ),
                ),
                (
                    "txval",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Taxable Value"
                    ),
                ),
                (
                    "cgst",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="Amount - Central Tax",
                    ),
                ),
                (
                    "sgst",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="Amount - State/UT Tax",
                    ),
                ),
                ("irn", models.CharField(max_length=80, null=True, verbose_name="IRN")),
                ("irn_date", models.DateField(null=True, verbose_name="IRN Date")),
                (
                    "srctype",
                    models.CharField(
                        max_length=15, null=True, verbose_name="Source Type (E-Invoice)"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gstr1_portal",
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.CreateModel(
            name="IkeaGSTR1Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inum", models.CharField(max_length=30, verbose_name="Invoice No")),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "txval",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="Taxable Value"
                    ),
                ),
                ("stock_id", models.CharField(max_length=50, verbose_name="UQC")),
                ("qty", models.IntegerField(verbose_name="Quantity")),
                (
                    "rt",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=12,
                        verbose_name="Tax - Central Tax",
                    ),
                ),
                ("type", models.CharField(max_length=50, verbose_name="Type")),
                ("hsn", models.CharField(max_length=50, verbose_name="HSN")),
                (
                    "desc",
                    models.CharField(
                        max_length=255, null=True, verbose_name="HSN Description"
                    ),
                ),
                (
                    "credit_note_no",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Debit/Credit No"
                    ),
                ),
                (
                    "original_invoice_no",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Original Invoice No"
                    ),
                ),
                (
                    "party_id",
                    models.CharField(max_length=100, verbose_name="Outlet Code"),
                ),
                (
                    "party_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Outlet Name"
                    ),
                ),
                (
                    "ctin",
                    models.CharField(
                        max_length=20, null=True, verbose_name="GSTIN of Recipient"
                    ),
                ),
                (
                    "cgst",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="Amount - Central Tax",
                    ),
                ),
                (
                    "sgst",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="Amount - State/UT Tax",
                    ),
                ),
                (
                    "inv_amt",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        verbose_name="Total Invoice Amount",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
            ],
            options={
                "db_table": "ikea_gstr1_report",
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                ("code", models.CharField(max_length=10)),
                ("master_code", models.CharField(blank=True, max_length=10, null=True)),
                ("name", models.CharField(blank=True, max_length=80, null=True)),
                ("type", models.CharField(db_default="shop", max_length=10)),
                ("addr", models.CharField(blank=True, max_length=150, null=True)),
                ("pincode", models.IntegerField(blank=True, null=True)),
                ("ctin", models.CharField(blank=True, max_length=20, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "company",
                        "code",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Party",
            },
        ),
        migrations.CreateModel(
            name="PartyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="Party Code")),
                (
                    "master_code",
                    models.CharField(
                        max_length=10, null=True, verbose_name="Party Master Code"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Party Name"
                    ),
                ),
                (
                    "addr",
                    models.CharField(max_length=150, null=True, verbose_name="Address"),
                ),
                (
                    "beat",
                    models.CharField(max_length=80, null=True, verbose_name="Beat"),
                ),
                (
                    "ctin",
                    models.CharField(
                        max_length=20, null=True, verbose_name="GSTIN Number"
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, null=True, verbose_name="Phone"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
            ],
            options={
                "db_table": "party_report",
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                ("inum", models.CharField(max_length=20)),
                ("party_id", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("amt", models.DecimalField(decimal_places=2, max_digits=12)),
                ("ctin", models.CharField(blank=True, max_length=20, null=True)),
                ("irn", models.CharField(blank=True, max_length=80, null=True)),
                ("gst_period", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "type",
                    models.CharField(db_default="purchase", max_length=15, null=True),
                ),
                ("ref", models.CharField(max_length=15, null=True)),
                (
                    "tds",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "tcs",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "company",
                        "inum",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
                (
                    "party",
                    models.ForeignObject(
                        from_fields=("company", "party_id"),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.party",
                        to_fields=("company", "code"),
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Purchase",
            },
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                ("inum", models.CharField(max_length=20)),
                ("party_id", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("amt", models.DecimalField(decimal_places=2, max_digits=12)),
                ("ctin", models.CharField(blank=True, max_length=20, null=True)),
                ("irn", models.CharField(blank=True, max_length=80, null=True)),
                ("gst_period", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "roundoff",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("type", models.CharField(max_length=15)),
                (
                    "tds",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "tcs",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "company",
                        "inum",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
                (
                    "party",
                    models.ForeignObject(
                        from_fields=("company", "party_id"),
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.party",
                        to_fields=("company", "code"),
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sales",
            },
        ),
        migrations.CreateModel(
            name="SalesRegisterReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inum", models.CharField(max_length=100, verbose_name="BillRefNo")),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "party_id",
                    models.CharField(max_length=100, verbose_name="Party Code"),
                ),
                (
                    "party_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Party Name"
                    ),
                ),
                ("type", models.CharField(max_length=50, verbose_name="Type")),
                (
                    "amt",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Bill Amount + Credit Adjustment",
                    ),
                ),
                (
                    "ctin",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Party GSTIN"
                    ),
                ),
                (
                    "tcs",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="TCS Amt",
                    ),
                ),
                (
                    "tds",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="TDS-194R Amt",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Net Tax"
                    ),
                ),
                (
                    "schdisc",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="SchDisc",
                    ),
                ),
                (
                    "cashdisc",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="CashDisc",
                    ),
                ),
                (
                    "btpr",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="BTPR SchDisc",
                    ),
                ),
                (
                    "outpyt",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="OutPyt Adj",
                    ),
                ),
                (
                    "ushop",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="Ushop Redemption",
                    ),
                ),
                (
                    "pecom",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="Adjustments",
                    ),
                ),
                (
                    "roundoff",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="RoundOff",
                    ),
                ),
                (
                    "other_discount",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="Other Discount (DisFinAdj + ReversedPayout)",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
            ],
            options={
                "db_table": "salesregister_report",
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("name", models.CharField(max_length=20)),
                ("hsn", models.CharField(max_length=20, null=True)),
                ("desc", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "rt",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=1,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "standard_rate",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "company",
                        "name",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Stock",
            },
        ),
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                ("inum", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("godown", models.CharField(max_length=20, null=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "company",
                        "inum",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_id", models.CharField(max_length=10)),
                ("qty", models.IntegerField()),
                (
                    "txval",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "rt",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=1,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "bill_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                (
                    "pur_bill_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                (
                    "adj_bill_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
                (
                    "purchase",
                    models.ForeignObject(
                        from_fields=("company", "pur_bill_id"),
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.purchase",
                        to_fields=("company", "inum"),
                    ),
                ),
                (
                    "sales",
                    models.ForeignObject(
                        from_fields=("company", "bill_id"),
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="app.sales",
                        to_fields=("company", "inum"),
                    ),
                ),
                (
                    "stock",
                    models.ForeignObject(
                        from_fields=("company", "stock_id"),
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.stock",
                        to_fields=("company", "name"),
                    ),
                ),
                (
                    "stock_adjustment",
                    models.ForeignObject(
                        from_fields=("company", "adj_bill_id"),
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.stockadjustment",
                        to_fields=("company", "inum"),
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockHsnRateReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_id",
                    models.CharField(max_length=8, verbose_name="Product Code"),
                ),
                ("hsn", models.CharField(max_length=8, verbose_name="HSN")),
                (
                    "rt",
                    models.DecimalField(
                        decimal_places=1, max_digits=12, verbose_name="Tax Rate"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
            ],
            options={
                "db_table": "stockhsnrate_report",
            },
            bases=(models.Model, typing.Generic),
        ),
    ]
