# Generated by Django 5.1.1 on 2025-10-10 10:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GSTR1Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("inum", models.CharField(max_length=100, verbose_name="Invoice No")),
                (
                    "txval",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Taxable Value"
                    ),
                ),
                ("stock_id", models.CharField(max_length=50, verbose_name="UQC")),
                ("qty", models.IntegerField(verbose_name="Quantity")),
                (
                    "rt",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Tax - Central Tax",
                    ),
                ),
                ("type", models.CharField(max_length=50, verbose_name="Type")),
                ("hsn", models.CharField(max_length=50, verbose_name="HSN")),
                (
                    "desc",
                    models.CharField(max_length=255, verbose_name="HSN Description"),
                ),
                (
                    "credit_note_no",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Debit/Credit No"
                    ),
                ),
                (
                    "original_invoice_no",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Original Invoice No"
                    ),
                ),
                (
                    "party_id",
                    models.CharField(max_length=100, verbose_name="Outlet Code"),
                ),
                (
                    "party_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Outlet Name"
                    ),
                ),
                (
                    "ctin",
                    models.CharField(
                        max_length=20, null=True, verbose_name="GSTIN of Recipient"
                    ),
                ),
                (
                    "cgst",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Amount - Central Tax",
                    ),
                ),
                (
                    "sgst",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Amount - State/UT Tax",
                    ),
                ),
            ],
            options={
                "db_table": "gstr1_report",
            },
        ),
        migrations.CreateModel(
            name="SalesRegisterReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("inum", models.CharField(max_length=100, verbose_name="BillRefNo")),
                (
                    "party_id",
                    models.CharField(max_length=100, verbose_name="Party Code"),
                ),
                (
                    "party_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Party Name"
                    ),
                ),
                ("type", models.CharField(max_length=50, verbose_name="Type")),
                (
                    "amt",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Bill Amount + Credit Adjustment",
                    ),
                ),
                (
                    "ctin",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Party GSTIN"
                    ),
                ),
                (
                    "tcs",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="TCS Amt",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Net Tax"
                    ),
                ),
                (
                    "schdisc",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="SchDisc",
                    ),
                ),
                (
                    "cashdisc",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="CashDisc",
                    ),
                ),
                (
                    "btpr",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="BTPR SchDisc",
                    ),
                ),
                (
                    "outpyt",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="OutPyt Adj",
                    ),
                ),
                (
                    "ushop",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Ushop Redemption",
                    ),
                ),
                (
                    "pecom",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Adjustments",
                    ),
                ),
                (
                    "roundoff",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="RoundOff",
                    ),
                ),
                (
                    "other_discount",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Other Discount (DisFinAdj + ReversedPayout)",
                    ),
                ),
            ],
            options={
                "db_table": "salesregister_report",
            },
        ),
    ]
