# Generated by Django 5.1.1 on 2025-10-19 16:19

import django.db.models.deletion
import typing
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "name",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_id", models.CharField(max_length=20)),
                ("sub_type", models.CharField(max_length=20)),
                ("type", models.CharField(blank=True, max_length=20, null=True)),
                ("amt", models.FloatField(db_default=0, default=0)),
                ("moc", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Discount",
            },
        ),
        migrations.CreateModel(
            name="DmgShtReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inum",
                    models.CharField(max_length=100, verbose_name="Damage Invoice No"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("damage", "damage"), ("shortage", "shortage")],
                        max_length=50,
                        verbose_name="Type (Damage or Shortage)",
                    ),
                ),
                (
                    "return_from",
                    models.CharField(
                        choices=[("market", "market"), ("rs", "rs")],
                        max_length=100,
                        verbose_name="Return From (Market/RS)",
                    ),
                ),
                ("date", models.DateField(verbose_name="Damage Date")),
                (
                    "party_id",
                    models.CharField(max_length=100, verbose_name="Retailer Code"),
                ),
                (
                    "party_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Retailer Name"
                    ),
                ),
                (
                    "stock_id",
                    models.CharField(max_length=50, verbose_name="Product Code"),
                ),
                (
                    "desc",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Product Name"
                    ),
                ),
                ("qty", models.IntegerField(verbose_name="Quantity")),
                (
                    "amt",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total TUR Value"
                    ),
                ),
                (
                    "plg",
                    models.CharField(
                        max_length=100, null=True, verbose_name="PLG (DETS,FNB,..)"
                    ),
                ),
                (
                    "credit_note_no",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Credit Note No"
                    ),
                ),
                (
                    "original_invoice_no",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Original Invoice No"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
            ],
            options={
                "db_table": "dmgsht_report",
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.AddField(
            model_name="company",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.group"
            ),
        ),
        migrations.CreateModel(
            name="IkeaGSTR1Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inum", models.CharField(max_length=30, verbose_name="Invoice No")),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "txval",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="Taxable Value"
                    ),
                ),
                ("stock_id", models.CharField(max_length=50, verbose_name="UQC")),
                ("qty", models.IntegerField(verbose_name="Quantity")),
                (
                    "rt",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Tax - Central Tax",
                    ),
                ),
                ("type", models.CharField(max_length=50, verbose_name="Type")),
                ("hsn", models.CharField(max_length=50, verbose_name="HSN")),
                (
                    "desc",
                    models.CharField(
                        max_length=255, null=True, verbose_name="HSN Description"
                    ),
                ),
                (
                    "credit_note_no",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Debit/Credit No"
                    ),
                ),
                (
                    "original_invoice_no",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Original Invoice No"
                    ),
                ),
                (
                    "party_id",
                    models.CharField(max_length=100, verbose_name="Outlet Code"),
                ),
                (
                    "party_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Outlet Name"
                    ),
                ),
                (
                    "ctin",
                    models.CharField(
                        max_length=20, null=True, verbose_name="GSTIN of Recipient"
                    ),
                ),
                (
                    "cgst",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Amount - Central Tax",
                    ),
                ),
                (
                    "sgst",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Amount - State/UT Tax",
                    ),
                ),
                (
                    "inv_amt",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        verbose_name="Total Invoice Amount",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
            ],
            options={
                "db_table": "ikea_gstr1_report",
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_id", models.CharField(max_length=10)),
                ("qty", models.IntegerField()),
                ("txval", models.FloatField(blank=True, null=True)),
                ("rt", models.FloatField(blank=True, null=True)),
                ("bill_id", models.CharField(blank=True, max_length=20, null=True)),
                ("pur_bill_id", models.CharField(blank=True, max_length=20, null=True)),
                ("adj_bill_id", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("master_code", models.CharField(blank=True, max_length=10, null=True)),
                ("name", models.CharField(blank=True, max_length=80, null=True)),
                ("type", models.CharField(db_default="shop", max_length=10)),
                ("addr", models.CharField(blank=True, max_length=150, null=True)),
                ("pincode", models.IntegerField(blank=True, null=True)),
                ("ctin", models.CharField(blank=True, max_length=20, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Party",
            },
        ),
        migrations.CreateModel(
            name="PartyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="Party Code")),
                (
                    "master_code",
                    models.CharField(
                        max_length=10, null=True, verbose_name="Party Master Code"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Party Name"
                    ),
                ),
                (
                    "addr",
                    models.CharField(max_length=150, null=True, verbose_name="Address"),
                ),
                (
                    "beat",
                    models.CharField(max_length=80, null=True, verbose_name="Beat"),
                ),
                (
                    "ctin",
                    models.CharField(
                        max_length=20, null=True, verbose_name="GSTIN Number"
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, null=True, verbose_name="Phone"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
            ],
            options={
                "db_table": "party_report",
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inum", models.CharField(max_length=20)),
                ("party_id", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("amt", models.FloatField(null=True)),
                ("ctin", models.CharField(blank=True, max_length=20, null=True)),
                ("irn", models.CharField(blank=True, max_length=80, null=True)),
                ("gst_period", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "type",
                    models.CharField(db_default="purchase", max_length=15, null=True),
                ),
                ("ref", models.CharField(max_length=15, null=True)),
                ("tds", models.FloatField(db_default=0, default=0)),
                ("tcs", models.FloatField(db_default=0, default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Purchase",
            },
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inum", models.CharField(max_length=20)),
                ("party_id", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("amt", models.FloatField(null=True)),
                ("ctin", models.CharField(blank=True, max_length=20, null=True)),
                ("irn", models.CharField(blank=True, max_length=80, null=True)),
                ("gst_period", models.CharField(blank=True, max_length=12, null=True)),
                ("discount", models.FloatField(db_default=0, default=0)),
                ("roundoff", models.FloatField(db_default=0, default=0)),
                (
                    "type",
                    models.CharField(db_default="sales", max_length=15, null=True),
                ),
                ("tds", models.FloatField(db_default=0, default=0)),
                ("tcs", models.FloatField(db_default=0, default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sales",
            },
        ),
        migrations.CreateModel(
            name="SalesRegisterReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inum", models.CharField(max_length=100, verbose_name="BillRefNo")),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "party_id",
                    models.CharField(max_length=100, verbose_name="Party Code"),
                ),
                (
                    "party_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Party Name"
                    ),
                ),
                ("type", models.CharField(max_length=50, verbose_name="Type")),
                (
                    "amt",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Bill Amount + Credit Adjustment",
                    ),
                ),
                (
                    "ctin",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Party GSTIN"
                    ),
                ),
                (
                    "tcs",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="TCS Amt",
                    ),
                ),
                (
                    "tds",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="TDS-194R Amt",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Net Tax"
                    ),
                ),
                (
                    "schdisc",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="SchDisc",
                    ),
                ),
                (
                    "cashdisc",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="CashDisc",
                    ),
                ),
                (
                    "btpr",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="BTPR SchDisc",
                    ),
                ),
                (
                    "outpyt",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="OutPyt Adj",
                    ),
                ),
                (
                    "ushop",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Ushop Redemption",
                    ),
                ),
                (
                    "pecom",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Adjustments",
                    ),
                ),
                (
                    "roundoff",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="RoundOff",
                    ),
                ),
                (
                    "other_discount",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Other Discount (DisFinAdj + ReversedPayout)",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
            ],
            options={
                "db_table": "salesregister_report",
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("hsn", models.CharField(max_length=20, null=True)),
                ("desc", models.CharField(blank=True, max_length=20, null=True)),
                ("rt", models.FloatField(null=True)),
                ("standard_rate", models.FloatField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Stock",
            },
        ),
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inum", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("godown", models.CharField(max_length=20, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockHsnRateReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_id",
                    models.CharField(max_length=8, verbose_name="Product Code"),
                ),
                ("hsn", models.CharField(max_length=8, verbose_name="HSN")),
                (
                    "rt",
                    models.DecimalField(
                        decimal_places=1, max_digits=12, verbose_name="Tax Rate"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
            ],
            options={
                "db_table": "stockhsnrate_report",
            },
            bases=(models.Model, typing.Generic),
        ),
    ]
