# Generated by Django 5.1.1 on 2025-10-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="party",
            unique_together={("company", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together={("company", "name")},
        ),
    ]
