# Generated by Django 5.1.1 on 2025-10-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="gstr1portal",
            table="gstr1_portal",
        ),
    ]
