# Generated by Django 5.2.7 on 2025-10-24 15:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gstr1portal",
            name="cgst",
            field=models.DecimalField(
                blank=True,
                db_default=Decimal("0.00"),
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Amount - Central Tax",
            ),
        ),
        migrations.AlterField(
            model_name="gstr1portal",
            name="sgst",
            field=models.DecimalField(
                blank=True,
                db_default=Decimal("0.00"),
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Amount - State/UT Tax",
            ),
        ),
        migrations.AlterField(
            model_name="ikeagstr1report",
            name="cgst",
            field=models.DecimalField(
                blank=True,
                db_default=Decimal("0.00"),
                decimal_places=3,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Amount - Central Tax",
            ),
        ),
        migrations.AlterField(
            model_name="ikeagstr1report",
            name="sgst",
            field=models.DecimalField(
                blank=True,
                db_default=Decimal("0.00"),
                decimal_places=3,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Amount - State/UT Tax",
            ),
        ),
        migrations.AlterField(
            model_name="salesregisterreport",
            name="btpr",
            field=models.DecimalField(
                blank=True,
                db_default=Decimal("0.00"),
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="BTPR SchDisc",
            ),
        ),
        migrations.AlterField(
            model_name="salesregisterreport",
            name="cashdisc",
            field=models.DecimalField(
                blank=True,
                db_default=Decimal("0.00"),
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="CashDisc",
            ),
        ),
        migrations.AlterField(
            model_name="salesregisterreport",
            name="other_discount",
            field=models.DecimalField(
                blank=True,
                db_default=Decimal("0.00"),
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Other Discount (DisFinAdj + ReversedPayout)",
            ),
        ),
        migrations.AlterField(
            model_name="salesregisterreport",
            name="outpyt",
            field=models.DecimalField(
                blank=True,
                db_default=Decimal("0.00"),
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="OutPyt Adj",
            ),
        ),
        migrations.AlterField(
            model_name="salesregisterreport",
            name="pecom",
            field=models.DecimalField(
                blank=True,
                db_default=Decimal("0.00"),
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Adjustments",
            ),
        ),
        migrations.AlterField(
            model_name="salesregisterreport",
            name="roundoff",
            field=models.DecimalField(
                blank=True,
                db_default=Decimal("0.00"),
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="RoundOff",
            ),
        ),
        migrations.AlterField(
            model_name="salesregisterreport",
            name="schdisc",
            field=models.DecimalField(
                blank=True,
                db_default=Decimal("0.00"),
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="SchDisc",
            ),
        ),
        migrations.AlterField(
            model_name="salesregisterreport",
            name="tcs",
            field=models.DecimalField(
                blank=True,
                db_default=Decimal("0.00"),
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="TCS Amt",
            ),
        ),
        migrations.AlterField(
            model_name="salesregisterreport",
            name="tds",
            field=models.DecimalField(
                blank=True,
                db_default=Decimal("0.00"),
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="TDS-194R Amt",
            ),
        ),
        migrations.AlterField(
            model_name="salesregisterreport",
            name="ushop",
            field=models.DecimalField(
                blank=True,
                db_default=Decimal("0.00"),
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Ushop Redemption",
            ),
        ),
    ]
