# Generated by Django 5.2.7 on 2025-10-26 18:21

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="sales",
            managers=[
                ("user_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="stock",
            name="desc",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
