# Generated by Django 5.1.1 on 2025-10-10 10:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gstr1report",
            name="inv_amt",
            field=models.DecimalField(
                blank=True,
                db_default=Decimal("0.00"),
                decimal_places=3,
                max_digits=12,
                null=True,
                verbose_name="Total Invoice Amount",
            ),
        ),
    ]
