# Generated by Django 5.1.1 on 2025-10-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_gstr1report_inv_amt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gstr1report",
            name="inv_amt",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=12,
                verbose_name="Total Invoice Amount",
            ),
            preserve_default=False,
        ),
    ]
