# Generated by Django 5.2.7 on 2025-10-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_sales_managers_alter_stock_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="desc",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
