# Generated by Django 5.1.1 on 2025-10-19 17:40

import django.db.models.deletion
import typing
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_party_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GSTR1Portal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(max_length=6, verbose_name="Period (MMYYYY)"),
                ),
                ("date", models.DateField(verbose_name="Invoice Date")),
                ("inum", models.CharField(max_length=30, verbose_name="Invoice No")),
                (
                    "type",
                    models.CharField(max_length=10, verbose_name="Type (b2b/cdnr)"),
                ),
                (
                    "ctin",
                    models.CharField(
                        max_length=20, null=True, verbose_name="GSTIN of Recipient"
                    ),
                ),
                (
                    "amt",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Invoice Amount"
                    ),
                ),
                (
                    "txval",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Taxable Value"
                    ),
                ),
                (
                    "cgst",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Amount - Central Tax",
                    ),
                ),
                (
                    "sgst",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Amount - State/UT Tax",
                    ),
                ),
                ("irn", models.CharField(max_length=80, null=True, verbose_name="IRN")),
                ("irn_date", models.DateField(null=True, verbose_name="IRN Date")),
                (
                    "srctype",
                    models.CharField(
                        max_length=15, null=True, verbose_name="Source Type (E-Invoice)"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.group"
                    ),
                ),
            ],
            options={
                "db_table": "gstr1_portal",
            },
            bases=(models.Model, typing.Generic),
        ),
    ]
