# Generated by Django 5.2.7 on 2025-10-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_gstr1portal_cgst_alter_gstr1portal_sgst_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="type",
            field=models.CharField(default="sales", max_length=15),
            preserve_default=False,
        ),
    ]
