# Generated by Django 5.1.1 on 2025-10-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_gstr1portal_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="gstr1portal",
            name="irn",
            field=models.CharField(max_length=80, null=True, verbose_name="IRN"),
        ),
        migrations.AddField(
            model_name="gstr1portal",
            name="irn_date",
            field=models.DateField(null=True, verbose_name="IRN Date"),
        ),
        migrations.AddField(
            model_name="gstr1portal",
            name="srctype",
            field=models.CharField(
                max_length=15, null=True, verbose_name="Source Type (E-Invoice)"
            ),
        ),
    ]
