# Generated by Django 5.2 on 2025-11-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_stock_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="gst_types",
            field=models.JSONField(default=list),
        ),
    ]
