# Generated by Django 5.1.1 on 2025-10-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_gstr1portal_irn_gstr1portal_irn_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gstr1portal",
            name="type",
            field=models.CharField(
                default="b2b", max_length=10, verbose_name="Type (b2b/cdnr)"
            ),
            preserve_default=False,
        ),
    ]
