# Generated by Django 5.1.1 on 2025-10-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_gstr1portal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="adj_bill_id",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="bill_id",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="pur_bill_id",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
