# Generated by Django 5.1.1 on 2025-10-10 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_gstr1report_inv_amt"),
    ]

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("master_code", models.CharField(blank=True, max_length=10, null=True)),
                ("name", models.CharField(blank=True, max_length=30, null=True)),
                ("type", models.CharField(db_default="shop", max_length=10)),
                ("addr", models.CharField(blank=True, max_length=150, null=True)),
                ("pincode", models.IntegerField(blank=True, null=True)),
                ("ctin", models.CharField(blank=True, max_length=20, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "verbose_name_plural": "Party",
            },
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "inum",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("amt", models.FloatField(null=True)),
                ("ctin", models.CharField(blank=True, max_length=20, null=True)),
                ("irn", models.CharField(blank=True, max_length=80, null=True)),
                ("gst_period", models.CharField(blank=True, max_length=12, null=True)),
                ("discount", models.FloatField(db_default=0, default=0)),
                ("roundoff", models.FloatField(db_default=0, default=0)),
                (
                    "type",
                    models.CharField(db_default="sales", max_length=15, null=True),
                ),
                ("tds", models.FloatField(db_default=0, default=0)),
                ("tcs", models.FloatField(db_default=0, default=0)),
                (
                    "party",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.party",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sales",
            },
        ),
    ]
