# Generated by Django 5.1.1 on 2025-10-10 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_party_sales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="party",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.party",
            ),
        ),
    ]
