# Generated by Django 5.2.7 on 2025-11-06 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_company_gst_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesChanges",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_id", models.CharField(db_index=True, max_length=20)),
                ("type", models.CharField(max_length=20)),
                ("notes", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
                (
                    "sales",
                    models.ForeignObject(
                        from_fields=("company", "bill_id"),
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.sales",
                        to_fields=("company", "inum"),
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
