# Generated by Django 5.2 on 2025-10-25 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_discount_amt_alter_ikeagstr1report_rt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="party",
            field=models.ForeignObject(
                from_fields=("company", "party_id"),
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.party",
                to_fields=("company", "code"),
            ),
        ),
    ]
