# Generated by Django 5.2.7 on 2025-11-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_saleschanges"),
    ]

    operations = [
        migrations.RenameField(
            model_name="saleschanges",
            old_name="type",
            new_name="field",
        ),
        migrations.AddField(
            model_name="saleschanges",
            name="new_value",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="saleschanges",
            name="old_value",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
