# Generated by Django 5.2 on 2025-10-25 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_sales_party"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="party",
            field=models.ForeignObject(
                default="",
                from_fields=("company", "party_id"),
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.party",
                to_fields=("company", "code"),
            ),
            preserve_default=False,
        ),
    ]
