# Generated by Django 5.1.1 on 2025-10-10 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_sales_party"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "name",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("hsn", models.CharField(max_length=20, null=True)),
                ("desc", models.CharField(blank=True, max_length=20, null=True)),
                ("rt", models.FloatField(null=True)),
                ("standard_rate", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Stock",
            },
        ),
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                (
                    "inum",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("godown", models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "inum",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("amt", models.FloatField(null=True)),
                ("ctin", models.CharField(blank=True, max_length=20, null=True)),
                ("irn", models.CharField(blank=True, max_length=80, null=True)),
                ("gst_period", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "type",
                    models.CharField(db_default="purchase", max_length=15, null=True),
                ),
                ("ref", models.CharField(max_length=15, null=True)),
                ("tds", models.FloatField(db_default=0, default=0)),
                ("tcs", models.FloatField(db_default=0, default=0)),
                (
                    "party",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.party",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Purchase",
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_type", models.CharField(max_length=20)),
                ("type", models.CharField(blank=True, max_length=20, null=True)),
                ("amt", models.FloatField(db_default=0, default=0)),
                ("moc", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="app.sales",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Discount",
                "unique_together": {("sub_type", "bill")},
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.IntegerField()),
                ("txval", models.FloatField(blank=True, null=True)),
                ("rt", models.FloatField(blank=True, null=True)),
                (
                    "bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invs",
                        to="app.sales",
                    ),
                ),
                (
                    "pur_bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invs",
                        to="app.purchase",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="invs",
                        to="app.stock",
                    ),
                ),
                (
                    "adj_bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invs",
                        to="app.stockadjustment",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("stock", "adj_bill"),
                    ("stock", "bill"),
                    ("stock", "pur_bill"),
                },
            },
        ),
    ]
