# Generated by Django 5.2.7 on 2025-11-08 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_rename_type_saleschanges_field_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleschanges",
            name="sales",
            field=models.ForeignObject(
                from_fields=("company", "bill_id"),
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.sales",
                to_fields=("company", "inum"),
            ),
        ),
    ]
