# Generated by Django 5.2 on 2025-10-25 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_sales_party"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="purchase",
            field=models.ForeignObject(
                from_fields=("company", "pur_bill_id"),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.purchase",
                to_fields=("company", "inum"),
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="sales",
            field=models.ForeignObject(
                from_fields=("company", "bill_id"),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory",
                to="app.sales",
                to_fields=("company", "inum"),
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="stock_adjustment",
            field=models.ForeignObject(
                from_fields=("company", "adj_bill_id"),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.stockadjustment",
                to_fields=("company", "inum"),
            ),
        ),
        migrations.AlterField(
            model_name="sales",
            name="party",
            field=models.ForeignObject(
                from_fields=("company", "party_id"),
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.party",
                to_fields=("company", "code"),
            ),
        ),
    ]
