# Generated by Django 5.1.1 on 2025-10-10 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_stock_stockadjustment_purchase_discount_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="bill",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invs",
                to="app.sales",
            ),
        ),
    ]
