# Generated by Django 5.2 on 2025-10-25 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_inventory_purchase_alter_inventory_sales_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="stock",
            field=models.ForeignObject(
                from_fields=("company", "stock_id"),
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.stock",
                to_fields=("company", "name"),
            ),
        ),
    ]
