# Generated by Django 5.1.1 on 2025-10-10 12:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_inventory_bill"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesregisterreport",
            name="tds",
            field=models.DecimalField(
                blank=True,
                db_default=Decimal("0.00"),
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="TDS-194R Amt",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invs",
                to="app.sales",
            ),
        ),
    ]
