# Generated by Django 5.1.1 on 2025-10-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_salesregisterreport_tds_alter_inventory_bill"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inventory",
            unique_together=set(),
        ),
    ]
