# Generated by Django 5.1.1 on 2025-10-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_inventory_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketReturnReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "inum",
                    models.CharField(max_length=100, verbose_name="Credit Note No"),
                ),
            ],
            options={
                "db_table": "marketreturn_report",
            },
        ),
    ]
