# Generated by Django 5.1.1 on 2025-10-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_marketreturnreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketreturnreport",
            name="amt",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Total TUR Value",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="marketreturnreport",
            name="credit_note_no",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Credit Note No"
            ),
        ),
        migrations.AddField(
            model_name="marketreturnreport",
            name="desc",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Product Name"
            ),
        ),
        migrations.AddField(
            model_name="marketreturnreport",
            name="original_invoice_no",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Original Invoice No"
            ),
        ),
        migrations.AddField(
            model_name="marketreturnreport",
            name="party_id",
            field=models.CharField(
                default=0, max_length=100, verbose_name="Retailer Code"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="marketreturnreport",
            name="party_name",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Retailer Name"
            ),
        ),
        migrations.AddField(
            model_name="marketreturnreport",
            name="plg",
            field=models.CharField(
                max_length=100, null=True, verbose_name="PLG (DETS,FNB,..)"
            ),
        ),
        migrations.AddField(
            model_name="marketreturnreport",
            name="qty",
            field=models.IntegerField(default=0, verbose_name="Quantity"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="marketreturnreport",
            name="return_from",
            field=models.CharField(
                choices=[("market", "market"), ("rs", "rs")],
                default=None,
                max_length=100,
                verbose_name="Return From (Market/RS)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="marketreturnreport",
            name="stock_id",
            field=models.CharField(
                default="", max_length=50, verbose_name="Product Code"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="marketreturnreport",
            name="type",
            field=models.CharField(
                choices=[("damage", "damage"), ("shortage", "shortage")],
                default="",
                max_length=50,
                verbose_name="Type (Damage or Shortage)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="marketreturnreport",
            name="date",
            field=models.DateField(verbose_name="Damage Date"),
        ),
        migrations.AlterField(
            model_name="marketreturnreport",
            name="inum",
            field=models.CharField(max_length=100, verbose_name="Damage Invoice No"),
        ),
    ]
