# Generated by Django 5.1.1 on 2025-10-11 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_marketreturnreport_amt_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MarketReturnReport",
            new_name="DmgShtReport",
        ),
    ]
