# Generated by Django 5.1.1 on 2025-10-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_rename_marketreturnreport_dmgshtreport"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="dmgshtreport",
            table="dmgsht_report",
        ),
    ]
