# Generated by Django 5.1.1 on 2025-10-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_dmgshtreport_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gstr1report",
            name="desc",
            field=models.CharField(
                max_length=255, null=True, verbose_name="HSN Description"
            ),
        ),
    ]
