# Generated by Django 5.1.1 on 2025-10-13 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_alter_gstr1report_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="adj_bill",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invs",
                to="app.stockadjustment",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="bill",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invs",
                to="app.sales",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="pur_bill",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invs",
                to="app.purchase",
            ),
        ),
    ]
