# Generated by Django 5.1.1 on 2025-10-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_inventory_adj_bill_alter_inventory_bill_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockHsnRateReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_id",
                    models.CharField(max_length=8, verbose_name="Product Code"),
                ),
                ("hsn", models.CharField(max_length=8, verbose_name="HSN")),
                (
                    "rt",
                    models.DecimalField(
                        decimal_places=1, max_digits=12, verbose_name="Tax Rate"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="gstr1report",
            name="inum",
            field=models.CharField(max_length=30, verbose_name="Invoice No"),
        ),
        migrations.AlterField(
            model_name="gstr1report",
            name="txval",
            field=models.DecimalField(
                decimal_places=3, max_digits=12, verbose_name="Taxable Value"
            ),
        ),
    ]
