# Generated by Django 5.1.1 on 2025-10-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_stockhsnratereport_alter_gstr1report_inum_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartyReport",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Party Code",
                    ),
                ),
                (
                    "master_code",
                    models.CharField(
                        max_length=10, null=True, verbose_name="Party Master Code"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Party Name"
                    ),
                ),
                (
                    "addr",
                    models.CharField(max_length=300, null=True, verbose_name="Address"),
                ),
                (
                    "beat",
                    models.CharField(max_length=80, null=True, verbose_name="Beat"),
                ),
                (
                    "ctin",
                    models.CharField(
                        max_length=20, null=True, verbose_name="GSTIN Number"
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, null=True, verbose_name="Phone"),
                ),
            ],
            options={
                "db_table": "party_report",
            },
        ),
        migrations.AlterModelTable(
            name="stockhsnratereport",
            table="stockhsnrate_report",
        ),
    ]
