# Generated by Django 5.1.1 on 2025-10-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_partyreport_alter_stockhsnratereport_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="name",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
