# Generated by Django 5.1.1 on 2025-10-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_alter_party_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partyreport",
            name="addr",
            field=models.CharField(max_length=150, null=True, verbose_name="Address"),
        ),
    ]
