# Generated by Django 5.1.1 on 2025-10-18 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_alter_partyreport_addr"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GSTR1Report",
            new_name="IkeaGSTR1Report",
        ),
        migrations.AlterModelTable(
            name="ikeagstr1report",
            table="ikea_gstr1_report",
        ),
    ]
